# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

variables:
  - VSEnterprise.ProductKey: 'Please Provide your own'

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: login
      inputs:
        containerRegistry: 'docker-hub'
        command: login
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Windows/Dockerfile'
        repository: theroks/azure-devops-windows-buildagent
        tags: |
          base-latest
          base-$(Build.BuildId)
        arguments: 'productkey=$(VSEnterprise.ProductKey)'